# Generated by Django 4.2.3 on 2024-05-31 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colour_picker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
