# Generated by Django 4.2.3 on 2024-06-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colour_picker_app', '0004_colourstore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColourStore',
            new_name='Colour_Store',
        ),
    ]
